app.url=http://localhost:3000
api.url=${app.url}/api/

browser.name=chromium
browser.headless=false
browser.slow-mo=0
browser.timeout=10s

spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.salesanalytics.autotests.api=INFO
